kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mynfs
  selector:
    matchLabels:
      release: "stable"
